# Generated by Django 2.0.2 on 2018-07-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('pes_id', models.AutoField(db_column='pes_id', primary_key=True, serialize=False, unique=True)),
                ('pes_nome', models.CharField(db_column='pes_nome', max_length=80)),
                ('pes_cpf', models.CharField(blank=True, db_column='pes_cpf', max_length=11, null=True)),
                ('pes_rg', models.CharField(blank=True, db_column='pes_rg', max_length=20, null=True)),
                ('pes_telefone', models.CharField(blank=True, db_column='pes_telefone', max_length=11, null=True)),
                ('pes_celular', models.CharField(blank=True, db_column='pes_celular', max_length=11, null=True)),
                ('pes_email', models.CharField(blank=True, db_column='pes_email', max_length=50, null=True)),
            ],
            options={
                'db_table': 'PESSOAS',
                'ordering': ['-pes_id'],
            },
        ),
    ]
