# Generated by Django 2.0.2 on 2018-07-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empregador',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('emp_cnjp', models.CharField(db_column='emp_cnpj', max_length=14, primary_key=True, serialize=False)),
                ('emp_razao_social', models.CharField(db_column='emp_razao_social', max_length=115)),
                ('emp_classificacao_tributaria', models.CharField(choices=[('001', 'Empresa enquadrada no regime de tributação Simples Nacional com tributação previdenciária substituída'), ('002', 'Empresa enquadrada no regime de tributação Simples Nacional com tributação previdenciária não substituída'), ('003', 'Empresa enquadrada no regime de tributação Simples Nacional com tributação previdenciária substituída e não substituída'), ('004', 'MEI - Micro Empreendedor Individual'), ('006', 'Agroindústria'), ('007', 'Produtor Rural Pessoa Jurídica'), ('008', 'Consórcio Simplificado de Produtores Rurais'), ('009', 'Órgão Gestor de Mão de Obra'), ('010', 'Entidade Sindical a que se refere a Lei 12.023/2009'), ('011', 'Associação Desportiva que mantém Clube de Futebol Profissional'), ('013', 'Banco, caixa econômica, sociedade de crédito, financiamento e investimento e\tdemais empresas relacionadas no parágrafo 1o do art. 22 da Lei 8.212./91'), ('014', 'Sindicatos em geral, exceto aquele classificado no código anterior'), ('021', 'Pessoa Física, exceto Segurado Especial'), ('022', 'Segurado Especial'), ('060', 'Missão Diplomática ou Repartição Consular de carreira estrangeira'), ('070', 'Empresa de que trata o Decreto 5.436/2005'), ('080', 'Entidade Beneficente/Isenta'), ('085', 'Ente Federativo, Orgãos da União, Autarquias e Fundações Públicas'), ('099', 'Pessoas Jurídicas em Geral')], db_column='emp_classficacao_tributaria', max_length=3)),
                ('emp_natureza_jur', models.CharField(db_column='emp_natureza_jur', max_length=5)),
                ('emp_contagem_dias_mens', models.CharField(db_column='emp_contagem_dias_mens', max_length=1)),
                ('emp_cooperativa', models.CharField(choices=[('00', 'Não é cooperativa'), ('01', 'Cooperativa de Trabalho'), ('02', 'Cooperativa de Produção'), ('03', 'Outras Cooperativas')], db_column='emp_cooperativa', max_length=2)),
                ('emp_construtora', models.BooleanField(db_column='emp_construtora', default=False)),
                ('emp_desoneracao_folha', models.BooleanField(db_column='emp_desoneracao_folha', default=False)),
                ('emp_regime_caixa', models.BooleanField(db_column='emp_regime_caixa', default=False)),
                ('emp_reg_eletronico', models.BooleanField(db_column='emp_reg_eletronico', default=False)),
                ('emp_fap', models.FloatField(db_column='emp_fap', max_length=14)),
                ('emp_situacao_pj', models.CharField(choices=[('00', 'Situação Normal'), ('01', 'Extinção'), ('02', 'Fusão'), ('03', 'Cisão'), ('04', 'Incorporação')], db_column='emp_situacao_pj', max_length=2)),
                ('emp_contato_nome', models.CharField(db_column='emp_contato_nome', max_length=60)),
                ('emp_contato_cpf', models.CharField(db_column='emp_contato_cpf', max_length=14)),
                ('emp_contato_fone', models.CharField(blank=True, db_column='emp_contato_fone', max_length=14, null=True)),
                ('emp_contato_celular', models.CharField(blank=True, db_column='emp_contato_celular', max_length=14, null=True)),
            ],
            options={
                'verbose_name': 'Empregador',
                'verbose_name_plural': 'Empregadores',
                'db_table': 'EMPREGADORES',
                'ordering': ['-emp_razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('est_id', models.AutoField(db_column='est_id', primary_key=True, serialize=False, unique=True)),
                ('est_tipo_insc', models.CharField(choices=[('J', 'Pessoa Jurídica'), ('C', 'CAEPF'), ('O', 'CNO')], db_column='est_tipo_insc', max_length=1)),
                ('est_inscricao', models.CharField(db_column='est_inscricao', max_length=18)),
                ('est_cnae_prep', models.CharField(db_column='est_cnae_prep', max_length=9)),
                ('est_aliquota_rat', models.CharField(db_column='est_aliquota_rat', max_length=3)),
                ('est_fap', models.CharField(blank=True, db_column='est_fap', max_length=23, null=True)),
                ('est_cep', models.CharField(blank=True, db_column='est_cep', max_length=9, null=True)),
                ('est_logradouro', models.CharField(blank=True, db_column='est_logradouro', max_length=80, null=True)),
                ('est_numero', models.CharField(blank=True, db_column='est_numero', max_length=8, null=True)),
                ('est_bairro', models.CharField(blank=True, db_column='est_bairro', max_length=30, null=True)),
                ('est_complemento', models.CharField(blank=True, db_column='est_complemento', max_length=30, null=True)),
                ('est_cidade', models.CharField(blank=True, db_column='est_cidade', max_length=30, null=True)),
                ('est_estado', models.CharField(blank=True, db_column='est_estado', max_length=30, null=True)),
                ('est_telefone', models.CharField(blank=True, db_column='est_telefone', max_length=14, null=True)),
                ('est_denominacao', models.CharField(blank=True, db_column='est_denominacao', max_length=80, null=True)),
            ],
            options={
                'db_table': 'ESTABELECIMENTOS',
                'ordering': ['-est_id'],
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('func_id', models.AutoField(db_column='func_id', primary_key=True, serialize=False, unique=True)),
                ('func_desc', models.CharField(db_column='func_desc', max_length=100)),
                ('func_cbo', models.CharField(db_column='func_cbo', max_length=6)),
                ('func_acum_cargos', models.CharField(blank=True, choices=[('1', 'Não Acumulável'), ('2', 'Profissional da Saúde'), ('3', 'Professor'), ('4', 'Técnico / Científico')], db_column='func_acum_cargos', max_length=1, null=True)),
                ('func_cont_tempo_espc', models.CharField(blank=True, choices=[('1', 'Não'), ('2', 'Professor (Infantil, Fundamental e Médio)'), ('3', 'Professor de Ensino Superior')], db_column='func_cont_tempo_espc', max_length=1, null=True)),
                ('func_cargo_exclusivo', models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], db_column='func_cargo_exclusivo', max_length=1, null=True)),
                ('func_lei_cargo', models.CharField(blank=True, db_column='func_lei_cargo', max_length=60, null=True)),
                ('func_data_lei_cargo', models.DateField(blank=True, db_column='func_data_lei_cargo', null=True)),
                ('func_situacao_lei_cargo', models.CharField(blank=True, choices=[('1', 'Criação'), ('2', 'Extinção'), ('3', 'Reestruturação')], db_column='func_situacao_lei_cargo', max_length=1, null=True)),
            ],
            options={
                'db_table': 'FUNCOES',
                'ordering': ['-func_id'],
            },
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('lot_codigo', models.CharField(db_column='lot_id', max_length=30, primary_key=True, serialize=False)),
                ('lot_tipo', models.CharField(choices=[('O01', 'Setor, departamento, estabelecimento ou conjunto de estabelecimentos do contribuinte, inclusive administração, no caso de cooperativa de trabalho, obras próprias de construção civil da Pessoa Jurídica e dependências do próprio trabalhador (trabalho remoto).'), ('O02', 'Obra de Construção Civil (Empreitada Parcial ou Sub-empreitada)'), ('003', 'Pessoa Física Tomadora de Serviços prestados mediante cessão de mão de obra, exceto contratante de cooperativa'), ('004', 'Pessoa Jurídica Tomadora de Serviços prestados mediante cessão de mão de obra, exceto contratante de cooperativa, nos termos da lei 8.212/1991'), ('005', 'Pessoa Jurídica Tomadora de Serviços prestados por cooperados por intermédio de cooperativa de trabalho, exceto aqueles prestados a entidade beneficente/isenta'), ('006', 'Entidade beneficente/isenta Tomadora de Serviços prestados por cooperados por intermédio de cooperativa de trabalho'), ('007', 'Pessoa Física tomadora de Serviços prestados por Cooperados por intermédio de Cooperativa de Trabalho'), ('008', 'Operador Portuário'), ('009', 'Empresa Contratante de Avulsos não portuários por intermédio do Sindicato'), ('010', 'Embarcação inscrita no Registro Especial Brasileiro (REB)'), ('021', 'Classificação da atividade econômica ou obra própria de construção civil da Pessoa Física'), ('024', 'Residência/Outros do Empregador Doméstico'), ('090', 'Lotação fora do País')], db_column='lot_tipo', max_length=3)),
                ('lot_cod_fpas', models.CharField(db_column='lot_cod_fpas', max_length=3)),
                ('lot_cod_terceiros', models.CharField(db_column='lot_cod_terceiros', max_length=4)),
            ],
            options={
                'db_table': 'LOTACOES',
                'ordering': ['-lot_codigo'],
            },
        ),
        migrations.CreateModel(
            name='Sindicato',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('sind_codigo', models.CharField(db_column='sind_codigo', max_length=45, primary_key=True, serialize=False)),
                ('sind_nome', models.CharField(db_column='sind_nome', max_length=60)),
                ('sind_cnpj', models.CharField(db_column='sind_cnpj', max_length=14)),
            ],
            options={
                'db_table': 'SINDICATOS',
                'ordering': ['-sind_nome'],
            },
        ),
        migrations.CreateModel(
            name='TomadorServico',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('tom_inscricao', models.CharField(db_column='tom_inscricao', max_length=18, primary_key=True, serialize=False)),
                ('tom_nome', models.CharField(db_column='tom_nome', max_length=45)),
                ('tom_codigo_gps', models.CharField(db_column='tom_codigo_gps', max_length=4)),
                ('tom_cep', models.CharField(blank=True, db_column='tom_cep', max_length=9, null=True)),
                ('tom_logradouro', models.CharField(db_column='tom_logradouro', max_length=80)),
                ('tom_numero', models.CharField(blank=True, db_column='tom_numero', max_length=8, null=True)),
                ('tom_bairro', models.CharField(blank=True, db_column='tom_bairro', max_length=30, null=True)),
                ('tom_complemento', models.CharField(blank=True, db_column='tom_complemento', max_length=30, null=True)),
                ('tom_cidade', models.CharField(blank=True, db_column='tom_cidade', max_length=30, null=True)),
                ('tom_estado', models.CharField(blank=True, db_column='tom_estado', max_length=30, null=True)),
                ('colaboradores', models.ManyToManyField(to='colaboradores.Contratado')),
            ],
            options={
                'db_table': 'TOMADORES_SERVICOS',
                'ordering': ['-tom_nome'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('tur_codigo', models.CharField(db_column='tur_codigo', max_length=30, primary_key=True, serialize=False)),
                ('tur_hora_entrada', models.TimeField(db_column='tur_hora_entrada')),
                ('tur_hora_saida', models.TimeField(db_column='tur_hora_saida')),
                ('tur_intervalo_entrada', models.TimeField(db_column='tur_intervalo_entrada')),
                ('tur_intervalo_saida', models.TimeField(db_column='tur_intervalo_saida')),
            ],
            options={
                'db_table': 'TURNOS',
                'ordering': ['-tur_codigo'],
            },
        ),
    ]
