# Generated by Django 2.0.2 on 2018-07-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20180717_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordemservico',
            name='qrcode',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode'),
        ),
    ]
