# Generated by Django 2.0.2 on 2018-07-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_auto_20180719_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalordemservico',
            name='tipo_servico',
            field=models.CharField(choices=[('1', 'Troca de tela - completa'), ('2', 'Troca de touch'), ('3', 'Troca de LCD'), ('4', 'Troca auricular'), ('5', 'Troca microfone'), ('6', 'Troca bateria interna'), ('7', 'Troca carcaça - completa'), ('8', 'Troca carcaça - frontal'), ('9', 'Troca carcaça - traseira'), ('10', 'Troca componente - SMD'), ('11', 'Banho ultrasônico'), ('12', 'Troca auto-falante'), ('13', 'Software - atualização'), ('14', 'Software - reinstalação'), ('15', 'Software - conta google'), ('16', 'Software - genérico')], db_column='tipo_servico', max_length=2),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/qrcode'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_servico',
            field=models.CharField(choices=[('1', 'Troca de tela - completa'), ('2', 'Troca de touch'), ('3', 'Troca de LCD'), ('4', 'Troca auricular'), ('5', 'Troca microfone'), ('6', 'Troca bateria interna'), ('7', 'Troca carcaça - completa'), ('8', 'Troca carcaça - frontal'), ('9', 'Troca carcaça - traseira'), ('10', 'Troca componente - SMD'), ('11', 'Banho ultrasônico'), ('12', 'Troca auto-falante'), ('13', 'Software - atualização'), ('14', 'Software - reinstalação'), ('15', 'Software - conta google'), ('16', 'Software - genérico')], db_column='tipo_servico', max_length=2),
        ),
    ]
