# Generated by Django 2.0.2 on 2018-07-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_auto_20180720_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalordemservico',
            name='hospedagem',
            field=models.CharField(blank=True, db_column='hospedagem', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='hospedagem',
            field=models.CharField(blank=True, db_column='hospedagem', max_length=3, null=True),
        ),
    ]
