# Generated by Django 2.0.2 on 2018-07-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_auto_20180720_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalordemservico',
            name='hospedagem',
            field=models.CharField(blank=True, db_column='hospedagem', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='hospedagem',
            field=models.CharField(blank=True, db_column='hospedagem', max_length=4, null=True),
        ),
    ]
