# Generated by Django 2.0.2 on 2018-07-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_auto_20180720_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalordemservico',
            name='qrcode',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='qrcode',
        ),
    ]
