# Generated by Django 2.0.2 on 2018-07-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_auto_20180720_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalordemservico',
            name='status',
            field=models.CharField(choices=[('1', 'Aberta'), ('2', 'Proximo a ser reparado'), ('3', 'Aguardando peça'), ('4', 'Em manutenção'), ('5', 'Reparo não autorizado'), ('6', 'Conserto inviável'), ('7', 'Aguardando autorização do cliente'), ('8', 'Pronto'), ('9', 'Entregue')], db_column='status', max_length=1),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('1', 'Aberta'), ('2', 'Proximo a ser reparado'), ('3', 'Aguardando peça'), ('4', 'Em manutenção'), ('5', 'Reparo não autorizado'), ('6', 'Conserto inviável'), ('7', 'Aguardando autorização do cliente'), ('8', 'Pronto'), ('9', 'Entregue')], db_column='status', max_length=1),
        ),
    ]
