# Generated by Django 2.0.2 on 2018-07-16 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('disp_id', models.AutoField(auto_created=True, db_column='disp_id', primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('marca', models.CharField(choices=[('000', '--------'), ('SAM', 'SAMSUNG'), ('APL', 'APPLE'), ('MOT', 'MOTOROLA'), ('LG', 'LG'), ('ALC', 'ALCATEL'), ('NKA', 'NOKIA'), ('XIO', 'XIOMI'), ('BLU', 'BLU'), ('MUT', 'MULTILASER'), ('GEN', 'GENERICO')], db_column='marca', max_length=3)),
                ('modelo', models.CharField(db_column='modelo', max_length=25)),
                ('imei', models.IntegerField(db_column='imei')),
                ('url_img', models.ImageField(blank=True, db_column='url_img', upload_to='static/img/dispositivos/')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'db_table': 'DISPOSITIVOS',
                'ordering': ['-disp_id'],
            },
        ),
    ]
