# Generated by Django 2.0.2 on 2018-07-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_auto_20180720_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='marca',
            field=models.CharField(choices=[('000', '--------'), ('SAM', 'SAMSUNG'), ('APL', 'APPLE'), ('MOT', 'MOTOROLA'), ('LG', 'LG'), ('ALC', 'ALCATEL'), ('NKA', 'NOKIA'), ('XIO', 'XIOMI'), ('BLU', 'BLU'), ('MUT', 'MULTILASER'), ('GEN', 'GENERICO'), ('CHN', 'CHINES'), ('ASU', 'ASUS')], db_column='marca', max_length=3),
        ),
    ]
