# Generated by Django 2.0.2 on 2018-07-16 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empregador', '0001_initial'),
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratado',
            name='estabelecimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empregador.Estabelecimento'),
        ),
        migrations.AddField(
            model_name='contratado',
            name='funcao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empregador.Funcao'),
        ),
        migrations.AddField(
            model_name='contratado',
            name='lotacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empregador.Lotacao'),
        ),
        migrations.AddField(
            model_name='contratado',
            name='sindicato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empregador.Sindicato'),
        ),
    ]
