# Generated by Django 2.0.2 on 2018-07-17 19:43

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_auto_20180716_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratado',
            name='con_remuneracao_outra_empresa_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='contratado',
            name='con_salario_mensal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Brazilian Real')], default='BRL', editable=False, max_length=3),
        ),
    ]
